services:
    
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

# sudo docker-compose -f certbot-docker-compose.yml run --rm  certbot certonly --webroot --webroot-path /var/www/certbot/ --force-renewal --email rahul@dronamobile.com -d ssl.rahulgharat.online --agree-tos --non-interactive